project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todolist/', include('todolist.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todolist/urls.py
from django.urls import path

from . import views

app_name = 'todolist'

urlpatterns = [
    path('painel/', views.painel, name='painel'),
    path('task/<int:id>/', views.task_view, name='task-view'),

    path('create/', views.create_view, name='create'),
    path('edit/', views.edit, name='edit'),
    path('done/', views.done, name='done'),
    path('undone/', views.undone, name='undone'),
    path('delete/', views.delete, name='delete'),
]

todolist/models.py
from django.contrib.auth.models import User
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=60)
    is_completed = models.BooleanField(default=False)
    create_at = models.DateField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self) -> str:
        return self.title

todolist/views.py
from django.shortcuts import redirect, render

from .models import Task, User


def painel(request):
    completed_tasks = Task.objects.filter(
        is_completed=True).order_by('last_updated')
    uncompleted_tasks = Task.objects.filter(
        is_completed=False).order_by('id')

    return render(request, 'todolist/pages/painel.html', context={
        'completed_tasks': completed_tasks,
        'uncompleted_tasks': uncompleted_tasks,
    })


def task_view(request, id):
    task = Task.objects.get(pk=id)

    return render(request, 'todolist/pages/task-view.html', context={
        'task': task,
    })


def edit(request):
    task_id = request.GET.get('task-id')
    task_title = request.GET.get('task-title')

    task = Task.objects.get(pk=task_id)
    task.title = task_title
    task.save()

    return redirect('todolist:painel')


def create_view(request):
    title = request.GET.get('new-card-title')
    user = User.objects.get(pk=request.user.pk)

    Task.objects.create(title=title, author=user)

    return redirect('todolist:painel')


def done(request):
    id_task = request.GET.get('task_id')

    task = Task.objects.get(pk=id_task)
    task.is_completed = True
    task.save()

    return redirect('todolist:painel')


def undone(request):
    id_task = request.GET.get('task_id')

    task = Task.objects.get(pk=id_task)
    task.is_completed = False
    task.save()

    return redirect('todolist:painel')


def delete(request):
    id_task = request.GET.get('task_id')

    task = Task.objects.get(pk=id_task)
    task.delete()

    return redirect('todolist:painel')

base_templates/templates/global/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
    <head>

        {% include 'todolist/partials/head.html' %}

        <title>{% block title %}{% endblock title %}</title>

    </head>

<body>

    {% include 'todolist/partials/header.html' %}

    {% block content %}{% endblock content %}
    
</body>
</html>

todolist/templates/todolist/pages/painel.html
{% extends 'global/base.html' %}

{% block title %}Painel{% endblock title %}

{% block content %}

<main>
    <div class="main-container container">
        <div class="main-content">
            
            {% include 'todolist/partials/create.html' %}

            <div class="card-group">
                
                {% if completed_tasks %}
                    <h2>Completed</h2>
                    {% for task in completed_tasks %}
                        {% include 'todolist/partials/post.html' %}
                    {% endfor %}
                {% endif %}

                {% if uncompleted_tasks %}
                    <h2>Uncompleted</h2>
                    {% for task in uncompleted_tasks %}
                        {% include 'todolist/partials/post.html' %}
                    {% endfor %}
                {% endif %}

            </div>
        </div>
    </div>
</main>

{% endblock content %}

todolist/templates/todolist/pages/task-view.html
{% extends 'global/base.html' %}

{% block title %}Task View{% endblock title %}

{% block content %}
    <div class="task-container container">
        <div class="task-content">
            <form class="card-form" action=" {% url 'todolist:edit' %} ">
                <input type="hidden" name="task-id" value="{{task.pk}}">
                <input class="input" type="text" name="task-title" value="{{task.title}}">
                <p><i>Digite o título da tarefa e aperte enter em seguida</i></p>
            </form>
        </div>
    </div>
{% endblock content %}

todolist/templates/todolist/partials/create.html
<div class="card-create">
    <form class="card-form" action=" {% url 'todolist:create' %} ">
        <input class="input" type="text" name="new-card-title">
        <p><i>Digite o título da tarefa e aperte enter em seguida</i></p>
    </form>
</div>

todolist/templates/todolist/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/brands.min.css" integrity="sha512-+oRH6u1nDGSm3hH8poU85YFIVTdSnS2f+texdPGrURaJh8hzmhMiZrQth6l56P4ZQmxeZzd2DqVEMqQoJ8J89A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/fontawesome.min.css" integrity="sha512-RvQxwf+3zJuNwl4e0sZjQeX7kUa3o82bDETpgVCH2RiwYSZVDdFJ7N/woNigN/ldyOOoKw8584jM4plQdt8bhA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/solid.min.css" integrity="sha512-uj2QCZdpo8PSbRGL/g5mXek6HM/APd7k/B5Hx/rkVFPNOxAQMXD+t+bG4Zv8OAdUpydZTU3UHmyjjiHv2Ww0PA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="{% static 'global/style.css' %}">

todolist/templates/todolist/partials/header.html
<header>
    <div class="header-container container">
        <div class="header-content">
            <a href="{% url 'todolist:painel' %}">
                <i class="fa-solid fa-clipboard-list header-icon"></i>
                <h1 class="header-title">Todo List</h1>
            </a>
        </div>
    </div>
</header>

todolist/templates/todolist/partials/post.html
<div class="card{% if task.is_completed %} finished{% endif %}">
    <div class="card-title">
        <span>{{ task.title }}</span>
    </div>
    <div class="card-crud">
        <span>
            <a class="card-edit" href=" {% url 'todolist:task-view' id=task.pk %}">Editar</a> |

            <a class="card-delete" href=" {% url 'todolist:delete' %}?task_id={{ task.pk }} ">Deletar</a> |

            {% if task.is_completed %}
                <a class="card-undone" href=" {% url 'todolist:undone' %}?task_id={{ task.pk }} ">Undone</a>
            {% else %}
                <a class="card-done" href=" {% url 'todolist:done' %}?task_id={{ task.pk }} ">Done</a>
            {% endif %}

        </span>
    </div>
</div>